[tool.poetry]
name = "jsonschema_testing"
version = "0.1.0"
description = ""
authors = ["Phillip Simonds <phillip.simonds@networktocode.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
termcolor = "^1.1.0"
jsonschema = "^3.2.0"
toml = "^0.10.0"
ipdb = "^0.13.2"
"ruamel.yaml" = "^0.16.10"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^19.10b0"

[tool.poetry.scripts]
test-schema = "jsonschema_testing.test_schema:main"

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
  | urls.py
  | settings.py
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
